### ISSUE TITLE
Rewrite spec suite

### ISSUE THREAD

**Issue by ariejan** [ariejan/imdb#39]
Rewrite specs to be more concise, less error-prone and up-to-date to current rspec standards.

This includes finding a suitable alternative for keeping copies of IMDB pages for testing.

**Comment by yez** [comment]
@ariejan Is more work to be done on this issue? I noticed that you mentioned " finding a suitable alternative for keeping copies of IMDB pages for testing", could you expand on that or is it no longer relevant?

**Comment by gumatias** [comment]
@yez I'm guessing by that he means start using VCR.
