### ISSUE TITLE
Imdb::BoxOffice cannot be instantiated in ruby 2.1.1, imdb version 0.8.2

### ISSUE THREAD

**Issue by Hammadk** [ariejan/imdb#70]
``` ruby
irb > Imdb::BoxOffice
NameError: uninitialized constant Imdb::BoxOffice
from .../.rbenv/versions/2.1.1/bin/irb:11:in `<main>'

irb > Imdb::MovieList
Imdb::MovieList < Object
```

**Comment by ariejan** [comment]
True, it's not included in the 0.8.2 release. For now, use the `master` branch instead. In your `Gemfile`:

    gem 'imdb', git: 'https://github.com/ariejan/imdb.git', branch: 'master'

I'll see if I can get around to releasing another version this week.
