### ISSUE TITLE
Relax nokogiri requirement

### ISSUE THREAD

**Issue by wulffeld** [ariejan/imdb#76]
Currently it's locked to 1.6.2.1 which is over a year old. Not sure why? Be great if this could get relaxed so we can use a newer nokogiri.

**Comment by knut2** [comment]
I used succesful nokogiri version 1.6.6.2 .

I would recommend to use an optimistic version constraint like 

    s.add_dependency 'nokogiri', '~> 1.6'

**Comment by bjornd** [comment]
+1

**Comment by kochd** [comment]
+1

**Comment by jarmo** [comment]
+1 - had to downgrade imdb gem to use newer version of nokogiri, because 1.6.2.1 didn't work on 64bit Windows.
