### ISSUE TITLE
Can you add an example to the tutorial or README about how to obtain the rating of a movie?

### ISSUE THREAD

**Issue by shevegen** [ariejan/imdb#83]
Hey ariejan,

Do you think you could add an example how to obtain the
rating of a movie that way, if only the name is known?

**Comment by ErnestK** [comment]
Hello @shevegen, 

I am try this gem a little bit.
Code looks simple, 
may be we should add it to readme.
What do you think?

1) if we know imdb_id
```
require 'imdb'

movie = Imdb::Movie.new(imdb_id)
p "#{movie.title.to_s} = #{movie.rating.to_s}"
```

2) if we khow only name, we should search for that name, 
search this is array, because we have in result more than 1 movie.

```
require 'imdb'

result = Imdb::Search.new('Breaking Bad')

p "result.movies.size = #{result.movies.size}"
result.movies.map do |movie|
  data = {
      'imdb_id' => movie.id,
      'title' => movie.title,
      'rating' => movie.rating
  }
  p "data = #{data}"
end

```
